POST http://localhost:3000/users
x-auth: Pass123
Content-Type: application/json

{
    "name": "Diego",
    "email": "alsgo@alsd.co",
    "password": "kkkk123445",
    "confirmPassword": "kkkk123445"
}